### ISSUE TITLE
use ipython for nameko shell

### ISSUE THREAD

**Issue by davidszotten** [onefinestay/nameko#210]
if available

see e.g. https://github.com/django/django/blob/9996158db467f9bef8243fcc36dc3602570e3613/django/core/management/commands/shell.py

**Comment by dAnjou** [comment]
I'd strongly vote for [bpython](http://www.bpython-interpreter.org/).

**Comment by davidszotten** [comment]
i guess we could look for various shells. the django code linked to above looks for ipython and bpython.

**Comment by mattbennett** [comment]
Merged with https://github.com/onefinestay/nameko/pull/252

**Comment by iho** [comment]
Hi! 
ipython is pretty good, but how about  this https://github.com/jonathanslenders/ptpython ?

**Comment by davidszotten** [comment]
rather than trying to keep up with a growing list of alternative repl's, maybe we can refactor things a little to make it easy for people to roll their own
