### ISSUE TITLE
Service suspension

### ISSUE THREAD

**Issue by baverman** [onefinestay/nameko#231]
Is there any way to suspend service execution at runtime? So it stops to process incoming messages?

**Comment by mattbennett** [comment]
There's no "suspend" per se, but the behaviour you describe is essentially just stopping (and presumably later restarting) a service.

**Comment by baverman** [comment]
> just stopping (and presumably later restarting) a service.

I am a dumb-dumb, missed a https://nameko.readthedocs.org/en/latest/cli.html#running-a-service section. I thought that `nameko run` starts all services it can find. Thank you.
