### ISSUE TITLE
By default, rabbitmq doesn't allow nameko to connect

### ISSUE THREAD

**Issue by vtbassmatt** [onefinestay/nameko#233]
At least on Windows (haven't tested elsewhere), rabbitmq's default installation denies guest access to the nameko vhost. This means that the Nameko docs are slightly misleading - there is one configuration step required before anything works :)

As administrator, run `rabbitmqctl add_vhost nameko` followed by `rabbitmqctl set_permissions -p nameko guest ".*" ".*" ".*"` in order to address the issue. I'll create a PR against the docs.

**Comment by mattbennett** [comment]
@vtbassmatt thanks for the bug report! This is addressed in https://github.com/onefinestay/nameko/pull/237, and we tried to make the error message friendlier too - https://github.com/onefinestay/nameko/pull/240

**Comment by vtbassmatt** [comment]
Great, thanks!
