### ISSUE TITLE
abstracting out serializer

### ISSUE THREAD

**Issue by ayoshi** [onefinestay/nameko#239]
Hi, first of all - I would like to thank you - I really love the API, it's kind of brilliant.

That noted - I think there is an important functionality lacking - abstraction over serialization protocol.
I see that RPC module has json hardcoded as serialization mechanism.

That presents several problems:

* it's hard to replace json with, for example ujson which is much faster. ( maybe even messagepack / cap'n'proto, etc )
* This disallows for serializing types like Decimal, which json does support through the use of custom encoder/decoder (ujson unfortunately doesn't).

Are there plan for abstracting it ? It doesn't seem to be much work, but I only glanced over rpc implementation, so I could be mistaken.

**Comment by mattbennett** [comment]
Thanks! Glad you like it :)

Abstracting the serialization is certainly something we'd like to do. Kombu supports pluggable serializers (see http://kombu.readthedocs.org/en/latest/userguide/serialization.html) but we lazily hardcoded to JSON for the serialization checks in the RPC implementation.

Removing the hardcoding should be straightforward and let you fall back to using kombu's serialization, which is a step in the right direction.

**Comment by ayoshi** [comment]
Agree, that definitely is a step in the right direction - though kombu's API for registering custom serializers is not pretty - it requires a module installed with a registered entry point, but at least it's doable.

There still would need to be a configuration setting in nameko' - since serializers are registered at a consumer level, which nameko  abstracts over.

**Comment by mattbennett** [comment]
You can also register them programmatically - http://kombu.readthedocs.org/en/latest/reference/kombu.serialization.html#kombu.serialization.register

Quite right about the config setting.

**Comment by ayoshi** [comment]
#244

**Comment by mattbennett** [comment]
Done and landed! (finally) Thanks @ayoshi
