### ISSUE TITLE
nameko and grequests?

### ISSUE THREAD

**Issue by davidbgk** [onefinestay/nameko#260]
I think there is an issue when using grequests with nameko, a simple import will cause the service to hang up and do not respond (actually the connection to amqp is not even established):

```python
import grequests
from nameko.events import event_handler


class TestService(object):
    name = 'test'

    @event_handler('foo', 'bar')
    def baz(self):
        pass
```

Otherwise all works fine so I guess it's maybe an issue upstream with gevent vs. amqp or something like that. Anyway, that might be of interest to document that if that's a limitation.

**Comment by davidszotten** [comment]
nameko is based on eventlet. not used grequests, but sounds very possible that they don't play nicely together. 

part of the point of using nameko is that you shouldn't need grequests, but rather use plain old requests, and get concurrency from having multiple workers running
