### ISSUE TITLE
Broadcast event example fails

### ISSUE THREAD

**Issue by morty** [onefinestay/nameko#269]
When I run the broadcast event example in `docs/examples/event_broadcast.py` it dies with the following message:

```
nameko.events.EventHandlerConfigurationError: Broadcast event handlers cannot be configured with reliable delivery.
```

**Comment by mattbennett** [comment]
Hi @morty, thanks for reporting. There is an open pull request that fixes this and a few of the other examples. See #250

It's currently blocked on a pytest-eventlet interaction bug, but a fix is in the works

**Comment by morty** [comment]
Hi @mattbennett, I don't think that PR fixes the issue I'm seeing. It just switches to using the print statement.

**Comment by morty** [comment]
@mattbennett OK, now I see events.py is changed too.
