### ISSUE TITLE
Random vhost for testing

### ISSUE THREAD

**Issue by mattbennett** [onefinestay/nameko#278]
We should start using a random vhost for test runs rather than trying to clean up an existing one.

``reset_rabbit_connections`` doesn't work properly because changes in the rabbit management interface aren't reflected immediately, so if the vhost is dirty there's nothing we can do about it.

It would be better to use a random vhost (unless requested otherwise) and still fail the test at the end if there are connections left over. ``reset_rabbit_connections`` should be removed.

**Comment by noisyboiler** [comment]
Hey @mattbennett. Why can't you use something like `rabbitmqctl delete_vhost test` at the end of a test run?

**Comment by mattbennett** [comment]
It's definitely preferable to use an API rather than wrapping a command line tool. Also I strongly suspect that ``rabbitmqctl`` either directly calls the API itself, or they both invoke the same underlying code.

**Comment by noisyboiler** [comment]
by "something like" i meant whatever underneath this command line call. what i'm curious about is why we can't create a test vhost and then kill it at the end of the run - seems much tidier than creating random ones.

**Comment by mattbennett** [comment]
``rabbitmqctl`` seems to be a wrapper around the erlang interpreter (https://github.com/rabbitmq/rabbitmq-server/blob/master/scripts/rabbitmqctl) so there's no benefit in going to what's "underneath" ``rabbitmqctl`` (same problems of the binary perhaps changing between platforms, not being on the path etc.)

As I said I suspect the fact that connections aren't immediately closed is just how things are implemented inside RabbitMQ, and doesn't have anything to do with the management API per se.

I agree that it would be *nicer* to use and then clean the same vhost between tests, but it doesn't seem to be possible, at least reliably.

**Comment by mattbennett** [comment]
Fixed in #288
