### ISSUE TITLE
understand the pytest in mock_container

### ISSUE THREAD

**Issue by jiamo** [onefinestay/nameko#285]
In nameko/testing/pytest.py 

```python

@pytest.fixture
def empty_config(request):
    from nameko.constants import AMQP_URI_CONFIG_KEY
    return {
        AMQP_URI_CONFIG_KEY: ""
    }


@pytest.fixture
def mock_container(request, empty_config):
    from mock import Mock
    from nameko.constants import SERIALIZER_CONFIG_KEY, DEFAULT_SERIALIZER
    from nameko.containers import ServiceContainer

    container = Mock(spec=ServiceContainer)
    container.config = empty_config
    container.config[SERIALIZER_CONFIG_KEY] = DEFAULT_SERIALIZER
    container.serializer = container.config[SERIALIZER_CONFIG_KEY]
    container.accept = [DEFAULT_SERIALIZER]
    return container
```
`empty_config` is a fixture. so what the `request` is? 

I found somewhere we use like this:
`container.config = {}` so the `{}` is passed as  the request?

**Comment by noisyboiler** [comment]
the `request` argument is part of the pytest framework and is an object you can use to introspect the "requesting" test function and/or add finalisers/teardown to them.

**Comment by mattbennett** [comment]
@noisyboiler is correct. The ``request`` parameter is superfluous in the ``empty_config`` fixture. It doesn't need to be there because it's not used, but also isn't affecting anything.

You will find that the following is correct:

``` python
def test_foo(mock_container, empty_config):
    assert mock_container.config == empty_config
```

**Comment by davidszotten** [comment]
can probably drop the redundant arg

**Comment by mattbennett** [comment]
Yeah we should
