### ISSUE TITLE
How and why to use backdoor? (or how to debug services)

### ISSUE THREAD

**Issue by rochacbruno** [onefinestay/nameko#304]
Hi,

I was trying to debug a running service, obviously failed putting **ipdb** inside services rpc methods, I ended using logging for debug.

But, I read about backdoor and tried to use.

in shell 1 I started the service
```
nameko run myservice --broker mybroker --backdoor-port 5050
```

then in another shell

```
nameko backdor localhost:5050
```

I was expecting to connect to the running service to be able to inspect (just like an ipdb session?)

but got.

```python
rochacbruno@CATHO:~$  nameko backdoor localhost:5050                                                                                                                
/bin/netcat
Traceback (most recent call last):
  File "/usr/local/bin/nameko", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/nameko/cli/main.py", line 26, in main
    args.main(args)
  File "/usr/local/lib/python2.7/dist-packages/nameko/cli/backdoor.py", line 39, in main
    if call(cmd) != 0:
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Maybe it is my misunderstanding about backdoors or on how to use it.

1. What is a backdoor and what is it for?
2. How is the way to debug running services? (there is an eager mode? verbose mode? redir stdout?)

Thanks so much

**Comment by davidszotten** [comment]
Hi,

There are a few options for debugging. (i)pdb is one of them, and `pdb.set_trace()` inside a service method should work just like any other python process. What didn't work as expected here?

The backdoor is a way to get a shell inside the process of a running service, possibly one that's been running for a while, and could even be enabled in production. It looks like you have encountered a bug (it shouldn't crash when not finding `netcat`, but instead try other alternatives. Maybe you could raise a separate issue about the crash, and post some more info (os, python version) to help us debug that.

When the backdoor works, you get a python shell prompt, from where you can interact with the objects inside the service process, e.g. the container, running workers, dependencies and other objects.

I think the mailing list https://groups.google.com/forum/#!forum/nameko-dev is a better place for the general debugging discussion. Perhaps you could post a simplified example of what you are trying with pdb and how it's not behaving as expected?

Obviously you could also separately add logging statements (or even `print`) for debugging, but we should be able to do better. If by "eager mode" you mean turning rpc calls into function calls that you can step through, that's something I've thought about but not really spent any time one.

Hope this helps,
David

**Comment by mattbennett** [comment]
Closing this issue to encourage discussion to move to the mailing list.

@rochacbruno if you have more questions please ask them there, and if you're able please report the backdoor bug (here, as an issue). Thanks
