### ISSUE TITLE
what extra config needed for nameko demo?

### ISSUE THREAD

**Issue by maloneguo** [onefinestay/nameko#305]
i start nmeko with the demo like :
$ nameko run helloworld
or
$ nameko shell
both 3.5 and 2.7 run into socket error as below :
is there extra config needed ?
```
....
File "/Users/xxxxxx/lab/python3fornameko/lib/python3.5/site-packages/amqp/transport.py", line 95, in __init__
    raise socket.error(last_err)
OSError: [Errno 61] ECONNREFUSED
```
```
....
   return TCPTransport(host, connect_timeout)
  File "D:\Python27\lib\site-packages\amqp\transport.py", line 95, in __init__
    raise socket.error(last_err)
socket.error: [Errno 10061] WSAECONNREFUSED
```

**Comment by noisyboiler** [comment]
I'm wondering whether you have RabbitMQ running yet?

**Comment by maloneguo** [comment]
thanks very much  , i'm new on nameko, the document not mentioned that at first page .

**Comment by noisyboiler** [comment]
no worries, our fault - we'll fix that.

**Comment by mattbennett** [comment]
There's been an issue open for a while - #276
