### ISSUE TITLE
Supporting broker-less client-server communication model

### ISSUE THREAD

**Issue by buriy** [onefinestay/nameko#306]
Hi devs,

I'd like to make a client-server version of the library,
that won't need any broker (AMQP / rabbitmq), but instead a simple client-server protocol like http://mprpc.readthedocs.org/
Is it possible? What should I do for this?

**Comment by davidszotten** [comment]
Hi Yuri,

I don't know anything about mprpc, but the nameko [http entrypoint](https://nameko.readthedocs.org/en/stable/built_in_extensions.html#http-get-post) is broker-less so you should be able to get some ideas there.

From a quick glance, mprpc is build on top of gevent, which might not play nicely with eventlet

**Comment by mattbennett** [comment]
The basic answer to this question is that it's possible to build a pair of nameko [extensions](http://nameko.readthedocs.io/en/stable/key_concepts.html#extensions) to handle any kind of protocol. The built-in RPC implementation uses a (very simple) nameko-defined protocol on top of AMQP, but you could use any protocol on on transport.

You need an [Entrypoint](http://nameko.readthedocs.io/en/stable/key_concepts.html#entrypoints) to handle incoming requests, and a client of some form to generate them. We don't really have docs on writing entrypoints, but you can study the `nameko.web` package for a simple example. It's built on `werkzeug` so what you find in that package is really the essence of an entrypoint.

I'm going to close this issue but please write to the [mailing list](https://groups.google.com/forum/#!forum/nameko-dev) if you decide to move forwards on this.

**Comment by buriy** [comment]
Hi @mattbennett @davidszotten ,
what you've provided is a server-side example, which is trivial to produce,
but I haven't seen any client-side example -- for HTTP you used curl, and for any RPC you always use AMQP.
Do I need just to use my chosen library (mprpc) client implementation , but replace server-side @rpc with my own server decorator?
Am I right that I also need to implement all in rpc package by myself then?
So, how to make it reusable for another RPC protocol? Do you have any API docs but this https://nameko.readthedocs.io/en/stable/built_in_extensions.html#rpc ?
Or is it free from any API obligations?
