### ISSUE TITLE
WebSocketHubProvider onConnect, onDisconnect

### ISSUE THREAD

**Issue by sideboltconor** [onefinestay/nameko#308]
Is there a way to receive websocket connect/disconnects events from WebSocketHubProvider dependency? Just "experimenting".

**Comment by davidszotten** [comment]
Hi,

**Edit (tldr)**: Not out of the box, but the pieces are there for you to build one if you want. Happy to guide you through this, though [the mailing list](https://groups.google.com/forum/#!forum/nameko-dev) is probably a better forum. 

**Original thoughts**:

The `WebSocketHubProvider` is a dependency provider. Listening to connection events probably maps best to a nameko entrypoint. We don't have one out of the box, but it should be relatively straightforward to build one yourself. Like the `WebSocketRpc` entrypoint it would make use of the `WebSocketServer`, which would need to be subclassed to have `add_websocket` and `remove_websocket` also look for providers and invoke them (as it does in `handle_websocket_request`).

As I said, if you're interested in building this and want a hand, please post to the mailing list and I'd be happy to help.

Best,
D

**Comment by sideboltconor** [comment]
Thank you kindly, I will do just that!
