### ISSUE TITLE
Middleware hook

### ISSUE THREAD

**Issue by tino** [onefinestay/nameko#309]
Would it be an idea to create a hook for http middleware? I am trying to consume the service from the browser, and therefore need to set CORS-headers. I got it working by returning custom Response objects instead of json, but doing this in middleware might make more sense.

**Comment by davidszotten** [comment]
Hi,

Nameko generally encourages extension by subclassing the `Extension`s and `Entrypoint`s. In this case, perhaps something like


```python
# HttpRequestHandler lives in nameko.web.handlers
class CorsHttpRequestHandler(HttpRequestHandler):  
    def response_from_result(self, *args, **kwargs):
        response = super(CorsHttpRequestHandler, self).response_from_result(*args, **kwargs)
        response.headers.add('Access-Control-Allow-Origin', '*')  # or whatever
        return response

cors_http = CorsHttpRequestHandler.decorator
```

**Comment by tino** [comment]
Ah, that sounds like a sensible approach. Thanks!

**Comment by tino** [comment]
For people wondering why this doesn't work (as I did): it won't work on 2.2.0, but you have to get the latest version from master...

**Comment by davidszotten** [comment]
re latest vs master: oh dear, that's been lying around for a while. will try to get a release out. thanks!

**Comment by harel** [comment]
If anyone gets here from Google, as I did, I used this code snippet as a base of a slightly larger component that auto registers OPTIONS endpoints and manages the various headers via decorator:

https://github.com/harel/nameko-cors

**Comment by harel** [comment]
Quick note - the above repository (https://github.com/harel/nameko-cors) has been updated to resolve a bug with OPTIONS requests going through the entire request flow instead of returning an empty body.

**Comment by lagelalegal** [comment]
@harel please you look the issue #471 about the `nameko-cors`.
