### ISSUE TITLE
Configration and general questions

### ISSUE THREAD

**Issue by genbits** [onefinestay/nameko#314]
Hi,

We want to experiment with your framework, and we have  a number of questions:

1. Why is the default **max_workers** argument set to 10 and not the default GreenPool value (1000)?
    Is there a reason for that? We are planning on using it in a high-concurrency environment where a few dozens to a few hundred of concurrent calls are executed at any given time.
2. Has the framework been tested for memory leaks?
3. Is the framework stable/production ready?
4. How do you monitor and control nameko? (supervisord/monit/etc). Since it does not run as a service, how do you implement start/stop/restart commands?

Thank you!

**Comment by davidszotten** [comment]
Hi,

1. I believe the reasons for a relatively low default were 
  a) the initial use-case (onefinestay) didn't have a huge number of concurrent activity, and 
  b) while the work was _mostly_ io-bound, there were tasks which used a non-trivial amount of cpu, which "starves" all other greenthreads. This was mitigated by not having too many concurrent workers. Depending on your use-case, a much larger number of concurrent workers may work fine.

2. Tested in the sense that it's been run in production environments that deal with sizeable amounts of data without any noticeable increase in long-term memory usage over time. During its development there have been memory leaks, but to my knowledge they have all been fixed. Of course no software is perfect but a memory leak would certainly be considered a bug.

3. Nameko has been used in production at onefinestay for several years at this point, running the main backend systems.

4. I generally run it with supervisord. If you launch your services with `nameko run myservice`, the runner installs a signalhandler for `SIGTERM` that requests a graceful shutdown (stops accepting requests, lets current requests finish and then exits)

The [mailing list](https://groups.google.com/forum/#!forum/nameko-dev) might be a better forum for continued discussion.

Best,
David

**Comment by genbits** [comment]
Thank you so much for the reply.
I will use the mailing list from now on for any questions.
Cheers
