### ISSUE TITLE
Timer Decorator and other Functionalities

### ISSUE THREAD

**Issue by kgrvamsi** [onefinestay/nameko#316]
Let me take a scenario where i want to know the number of scheduled threads running for a given program is there a way to know about that either from the cli or from any core module that the nameko have

In the given example lets take i have a function that i have the decorator timer which the interval is given for 10 secs to run so can the function access that interval variable inside the function

```
from nameko.timer import timer

@timer(interval=10)
def testing(self,interval):
  print interval
```

**Comment by mattbennett** [comment]
If I understand correctly there are two questions here:

Q1. Is there any way to know how many threads are running?

It depends what you mean. The `ServiceContainer._worker_pool` is the pool of Greenthreads used to run workers (i.e. the threads used to execute service methods). You can call `pool.running()` to find out how many _workers_ are currently active. I guess this is the metric you really want to know? If so, there are better ways to track the information, such as a `DependencyProvider` that increments a counter on `worker_setup` and decrements it again on `worker_teardown`.

Nameko uses threads for other things other than running workers too. Most entrypoint implementations  rely on a background thread (e.g. the `Timer`). If these threads are managed by nameko (which they should be, aren't guaranteed to be) you can find them in the `ServiceContainer._active_threads` and `ServiceContainer._protected_threads` attributes.

Q2. Can `@timer` decorated methods know what `interval` argument they were called with?

Not in the built-in implementation, but it's pretty easy to create a subclass that passes it in:

``` python
from nameko.timer import Timer

class AwareTimer(Timer):
    def handle_timer_tick(self):
        args = (self.interval,)
        kwargs = {}
        self.container.spawn_worker(self, args, kwargs)

aware_timer = AwareTimer.decorator
```
``` python
@aware_timer(interval=10)
def testing(self,interval):
  print interval  # works
```

The `timer` entrypoint is entirely declarative though, so why don't you do the following?

``` python
interval = 10

class Service:
    @timer(interval)
    def testing(self):
        print(interval)
``` 

The [user group](https://groups.google.com/forum/#!forum/nameko-dev) is a better place for these kind of questions. If you have any more, please ask them there.
