### ISSUE TITLE
Is there any way to call RPC in PHP?

### ISSUE THREAD

**Issue by erhuabushuo** [onefinestay/nameko#321]
Is there any way to call RPC in PHP?

**Comment by mattbennett** [comment]
It's certainly possible. There are PHP libraries for RabbitMQ that you could use to reimplement the logic in https://github.com/onefinestay/nameko/blob/master/nameko/standalone/rpc.py.

If you have more questions the mailing list (https://groups.google.com/forum/#!forum/nameko-dev) is the most appropriate place to ask them.
