### ISSUE TITLE
pub-sub: subscribe to unknown publishers

### ISSUE THREAD

**Issue by kodonnell** [onefinestay/nameko#330]
Say I have the typical `add` microservice which adds two numbers and returns the result. My understanding is that there's no real way of implementing this in a generic pub-sub way in nameko, as I can't tell the `add` service to listen to any broadcaster. Is this correct? If so, would it be possible to do something like:

```python
@event_handler(None, 'add')
def add(self, payload):
    return payload['x'] + payload['y']
```

To mean 'listen to any event with event_type of "add"'?

Alternatively, it looks like I could possibly achieve the same thing with (async) RPC.

Note: similar to #295, though that seemed to be for a different use case (multiple known services).

**Comment by mattbennett** [comment]
It is correct that you must specify the source service as well as the event type. But even if that wasn't the case, the nameko event handler (and the pub-sub pattern in general) doesn't support returning results to the dispatcher.

RPC is the way to achieve what you want here.

If you have more questions, the mailing list (https://groups.google.com/forum/#!forum/nameko-dev) is the best place to ask them.
