### ISSUE TITLE
Please upload a tarball or sdist to Pypi!  Pretty please?

### ISSUE THREAD

**Issue by zmrow** [onefinestay/nameko#332]
Would it be possible for you to upload a tarball or sdist to Pypi?  Would be super helpful!

**Comment by davidszotten** [comment]
hm. i thought we were... the deployment is done via travis. might be a bug.

https://pypi.python.org/pypi/nameko/2.2.0 has both

https://pypi.python.org/pypi/nameko/2.3.0 is wheel only

nothing changed on the deployment side between those. will try to investigate, though if you have time, maybe you could have a look through the travis logs to see if anything stands out

**Comment by zmrow** [comment]
I didn't see anything at the end of the current build's logs...  However I did find this line at the end of build 1895:
`Skipping a deployment with the pypi provider because this is not a tagged commit`

I'm not a travis user, so it's more than possible I missed something.

**Comment by davidszotten** [comment]
non-tagged just means a regular pull-request build. only releases (tagged commits) get deployed.

success: https://s3.amazonaws.com/archive.travis-ci.org/jobs/83554040/log.txt
500 error from the wheel upload: https://s3.amazonaws.com/archive.travis-ci.org/jobs/129506085/log.txt

looks like it might be a pypi issue:
https://mail.python.org/pipermail/distutils-sig/2016-June/029083.html

might be able to do the same on travis, but hard to experiment in this area

**Comment by zmrow** [comment]
Oh interesting!  Hmm.  Anything I could help out with?

**Comment by zmrow** [comment]
The 2.2 tarball got me unblocked, but I'd like to be on the latest - would another deployment possibly fix this?

**Comment by mattbennett** [comment]
I think Travis is smart enough not to reattempt the uploading on a subsequent build.  I've manually uploaded the missing files.

Why did you need them to be on PyPI (as opposed to just generating them from source)?

**Comment by zmrow** [comment]
Thanks so much!  My company has an import tool that is relatively picky about where and how it gets its packages.  Really appreciate it.

**Comment by mattbennett** [comment]
No sweat :)
