### ISSUE TITLE
Nameko hangs on execution of nested service call

### ISSUE THREAD

**Issue by noizex** [onefinestay/nameko#338]
Today I ran into weird case that manages to get nameko hung on executing nested service call. The flow is like this:

- external, standalone script executes N async calls to service A
- service A calls (sync) service B, which does something and returns 

I tried it with setup of 2 workers, so 2 containers are spawned for both Service A and Service B. 

The result is - I fire 8 very fast (in a loop) async calls to Service A, and don't wait for the result. This makes only 2 initial calls to ServiceA.run() and hangs there forever, stopping from processing remaining 6 calls.
Maybe I'm doing something really wrong here, I've been just trying nameko to see if it will work for us, but can't think of any reason why this shouldn't work. I attach debug log from nameko service, after what's logged there it just hangs. I also attach my test case that should result in the same behaviour when you run it.

I don't know anything about nameko internals, so it's hard to try and debug this case, so any help is welcome. 

[test_case.zip](https://github.com/onefinestay/nameko/files/332007/test_case.zip)
[nameko_service_log.txt](https://github.com/onefinestay/nameko/files/332004/nameko_service_log.txt)

**Comment by mattbennett** [comment]
I can't reproduce this locally.

What library versions, platform, python and RabbitMQ versions are you using?
Are you running the services with a config file?
What is the state of the Rabbit queues when it hangs?

**Comment by noizex** [comment]
I will have to check it on my work laptop, so this has to wait till Monday. I'm running nameko on OSX, installed from brew, so should be quite fresh version. AMQP is served by external server, and from what I remember the queue of these async calls stays filled. So for example if I did 100 async calls, and my nameko workers processed 5 of them and hung, there will be 95 messages in queue waiting. What's more, if I kill nameko process (which doesn't exit immediately on CTRL+C but waits for workes to "finish job" even though they shouldn't be doing anything) and restart, it will pick up next 5 jobs in line and hang on them. 

I will give more feedback on Monday - versions, state of AMQP between calls and so on.

**Comment by noizex** [comment]
Ok, so once again, it's OSX 10.11.5, I attached my pip freeze to the comment, RabbitMQ version 3.6.1. Services are indeed using config file, if I haven't zipped it last time there it is:
`AMQP_URI: 'amqp://...'`
`WEB_SERVER_ADDRESS: '0.0.0.0:8000'`
`rpc_exchange: 'nameko-rpc'`
`max_workers: 2`
`parent_calls_tracked: 10`

I attach screenshots of queues:
1 - just after starting nameko fresh
2 - when I execute "test.py" - it's important to note that I never consume responses from async call, just quit without waiting for result
3 - after I stop nameko, have to do it using 2 x CTRL+C, and it dumps this when it quits:

```
^C
stopping <ServiceContainer [service_a] at 0x10b009850>
stopping <ServiceContainer [service_b] at 0x10b0c0750>
stopped <ServiceContainer [service_b] at 0x10b0c0750> in 0.016s
^C
killing <ServiceContainer [service_a] at 0x10b009850>
already stopped <ServiceContainer [service_b] at 0x10b0c0750>
killing 2 active thread(s)
killing active thread for <Rpc [service_a.run] at 0x10b0097d0>
ran handler for <WorkerContext [service_a.run] at 0x10b0eca90> in 52.747s
ran worker <WorkerContext [service_a.run] at 0x10b0eca90> in 52.750s
<ServiceContainer [service_a] at 0x10b009850> thread killed by container
killing active thread for <Rpc [service_a.run] at 0x10b0097d0>
ran handler for <WorkerContext [service_a.run] at 0x10b0ec750> in 52.748s
ran worker <WorkerContext [service_a.run] at 0x10b0ec750> in 52.750s
<ServiceContainer [service_a] at 0x10b009850> thread killed by container```

4 - after starting nameko for the second time, it looks like 2 previously executed calls to Service A have returned to the queue and we're again exuecuting 2 out of 9, not 7. So this hangs even before acknowledging that initial call was successful (makes sense, as it doesn't execute any code after line 18: `self.test_service.test(cnt)`
![1-after_nameko_started](https://cloud.githubusercontent.com/assets/3256633/16373273/b3777f58-3c51-11e6-8bdb-a9a91a52a990.png)
![2-after_running_test](https://cloud.githubusercontent.com/assets/3256633/16373275/b64904fe-3c51-11e6-9020-b11b4ba58e34.png)
![3-after_stopping_nameko](https://cloud.githubusercontent.com/assets/3256633/16373278/b9189046-3c51-11e6-823c-74321427cd67.png)
![4-after_nameko_started_2nd_time](https://cloud.githubusercontent.com/assets/3256633/16373282/bc1d4bba-3c51-11e6-9914-41d642a46d0d.png)

**Comment by noizex** [comment]
Tracked it down a bit more, it hangs on RpcReply(), "Waiting for RPC reply event" after executing method in Service B. Unfortunately I have no idea why would it wait there, as that method ends immediately and just returns simple number. I guess something is wrong with my queues maybe? Does nameko require some specific rabbitmq config, or would work on basic one?

**Comment by noizex** [comment]
Allright, that RabbitMQ was my local version, I'm using server now that has 3.2.4, seems pretty old, maybe it doesn't have this confirm_publish extension and that's the reason. I will check on my local RabbitMQ and see if I can reproduce it.

**Comment by noizex** [comment]
And there it is, RabbitMQ from Ubuntu is 3.2.4 and doesn't work, my local version is 3.6.1 and works fine, looks like some missing feature then. Problem self-solved I guess..

**Comment by mattbennett** [comment]
The missing feature is more likely to be [consumer prefetch](https://www.rabbitmq.com/consumer-prefetch.html) rather than publish confirms. Prior to RabbitMQ 3.3.0 the prefetch count (which nameko sets to the same value as `max_workers`) is shared across the entire _connection_. That includes the reply listener, so you ended up with a deadlock.
