### ISSUE TITLE
Support optional parameters in RPC

### ISSUE THREAD

**Issue by grepsr** [onefinestay/nameko#339]
If there is a service method like this:
```
    @rpc
    def hello(self, a, b=None):
        return {'a': a, 'b': b}
```

The parameter "b" is an optional parameter. 
Right now, it looks like Nameko, needs the caller to pass ALL parameters to a function, even if they are optional. It responds with "IncorrectSignature".

Shouldn't optional parameters be allowed to be skipped?

**Comment by davidszotten** [comment]
optional parameters are supported, and the example above works for me

```
>>> n.rpc.greeting_service.hello(12)
{u'a': 12, u'b': None}
```

note that the first parameter `a` in your example _is_ required:

```
>>> n.rpc.greeting_service.hello()
# ...
# (as with regular python function calls, the `self` argument is included in the count)
IncorrectSignature: hello() takes at least 2 arguments (1 given)
```

**Comment by grepsr** [comment]
You are right, closing this now. I had forgotten to restart, nameko, duh! My bad!
