### ISSUE TITLE
Nameko.cli.main No Module

### ISSUE THREAD

**Issue by kgrvamsi** [onefinestay/nameko#343]
![image](https://cloud.githubusercontent.com/assets/1199031/17304413/1b1d5600-57eb-11e6-93f4-030d033d0ba9.png)

Not sure but tried with the nameko == 2.3.0/2.3.1

**Comment by davidszotten** [comment]
Hi,

We're going to need some more info to have any chance of helping you. To start with, could you specify your os+version, your python version, the steps you took to install nameko, the full command you are running above, and the full traceback. Also, for any terminal output, copy/pasting the _text_ is easier to deal with than taking screenshots.

**Comment by kgrvamsi** [comment]
@davidszotten  closing this issue because when i run via sudo command the command runs with no issues.Thanks for quick response
