### ISSUE TITLE
nameko.exceptions.RemoteError: UnicodeEncodeError 'ascii' codec can't encode character u'\u6bb5' in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by dxfmichaelgithub** [onefinestay/nameko#349]
nameko support non ascii character?

>>> n.rpc.greeting_service.hello("段")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/nameko/rpc.py", line 352, in __call__
    return reply.result()
  File "/usr/lib/python2.7/site-packages/nameko/rpc.py", line 338, in result
    raise deserialize(error)
RemoteError: UnicodeEncodeError 'ascii' codec can't encode character u'\u6bb5' in position 0: ordinal not in range(128)

**Comment by davidszotten** [comment]
Hi,

This is not a problem with nameko, but a bug in the example `GreetingService`: 

https://github.com/onefinestay/nameko/blob/master/docs/examples/helloworld.py#L8 calls ` "Hello, {}!".format(name)`, which fails with non-ascii `name`s. You can fix it by prefixing the string with `u`, (so `"uHello, {}!".format(name)`) or by calling `from __future__ import unicode_literals` at the top of the `helloworld.py`

Leaving this open, as we should get our examples fixed

**Comment by mattbennett** [comment]
Fixed by #350
