### ISSUE TITLE
cleanup_websocket bug

### ISSUE THREAD

**Issue by sideboltconor** [onefinestay/nameko#367]
It seems there is a bug in cleanup_websocket (websocket.py) which fails to remove a socket_id from the subscription list. 

```
def cleanup_websocket(self, socket_id):
    con = self.hub.connections.pop(socket_id, None)
    if con is not None:
        for channel in con.subscriptions:
            subs = self.hub.subscriptions.get(channel)
            if subs:
                subs.discard(channel) <-- This should be socket_id
```

Channel is being discarded from the list of socket_ids instead of the socket_id that is disconnecting.

**Comment by davidszotten** [comment]
nice catch. thanks

**Comment by sideboltconor** [comment]
Cheers.

**Comment by davidszotten** [comment]
let's leave open until the fix lands
